import React, { useEffect, useMemo, useState } from 'react';
import { Activity, AlertTriangle, CheckCircle2, Clock3, Gauge, Mail, RefreshCw, Server, XCircle, Zap } from 'lucide-react';
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { DashboardStats, Message, ServiceLog } from '../types';

interface Props { stats: DashboardStats | null; recentMessages: Message[]; onSelectMessage: (message: Message) => void; onNavigateToSend: () => void; onRefresh: () => void; isLoading: boolean; }
interface LiveMetrics { [key:string]: any }
type Section='overview'|'queues'|'domains'|'vmtas'|'jobs'|'reputation'|'logs';
const n=(v:any)=>Number(v||0); const fmt=(v:any)=>Math.round(n(v)).toLocaleString(); const pct=(v:any)=>`${n(v).toFixed(2)}%`;
const time=(v:string)=>{const d=new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'});};
const card='bg-[#101216] border border-[#242832] rounded-lg shadow-[0_8px_30px_rgba(0,0,0,.18)]';

export const PowerDashboardView:React.FC<Props>=({stats,recentMessages,onSelectMessage,onNavigateToSend,onRefresh,isLoading})=>{
 const [section,setSection]=useState<Section>('overview'); const [live,setLive]=useState<LiveMetrics>({}); const [messages,setMessages]=useState<Message[]>(recentMessages); const [logs,setLogs]=useState<ServiceLog[]>([]); const [samples,setSamples]=useState<any[]>([]);
 const refreshLive=async()=>{try{const base=import.meta.env.VITE_API_BASE_URL||''; const [mr,lr]=await Promise.all([fetch(`${base}/api/messages?limit=100`),fetch(`${base}/api/logs?limit=100`)]); if(mr.ok){const d=await mr.json();setMessages(d.messages||[]);} if(lr.ok){const d=await lr.json();setLogs(d.logs||[]);} const r=await fetch(`${base}/api/metrics?format=json`); if(r.ok){const d=await r.json();setLive(d);setSamples(p=>[...p,{t:time(new Date().toISOString()),queue:n(d.kumomta_queue_size),rate:n(d.kumomta_delivery_rate_per_second)}].slice(-40));}}catch(e){console.error('[PowerDashboard] live refresh failed',e);}};
 useEffect(()=>{refreshLive();const id=window.setInterval(refreshLive,2000);return()=>window.clearInterval(id);},[]);
 useEffect(()=>{if(recentMessages.length)setMessages(recentMessages);},[recentMessages]);
 const shown=messages.length?messages:recentMessages; const sent=n(stats?.totalSent),delivered=n(stats?.delivered),bounced=n(stats?.bounced),queue=n(live.kumomta_queue_size??stats?.queueSize),inFlight=n(live.kumomta_messages_in_flight),rate=n(live.kumomta_delivery_rate_per_second??stats?.sendingRatePerSec),active=n(live.kumomta_smtp_connection_pool_active),idle=n(live.kumomta_smtp_connection_pool_idle);
 const health=useMemo(()=>{if(stats?.kumoHealth==='offline')return['CRITICAL','text-red-400 bg-red-950/50'];if(n(stats?.bounceRate)>=5||queue>1000)return['DEGRADED','text-amber-400 bg-amber-950/50'];return['HEALTHY','text-emerald-400 bg-emerald-950/50'];},[stats?.kumoHealth,stats?.bounceRate,queue]);
 const domains=useMemo(()=>{const map=new Map<string,{total:number;delivered:number;bounced:number;deferred:number}>();shown.forEach(m=>{const d=(m.toEmail?.split('@')[1]||'unknown').toLowerCase();const x=map.get(d)||{total:0,delivered:0,bounced:0,deferred:0};x.total++;if(m.status==='DELIVERED')x.delivered++;if(m.status==='BOUNCED')x.bounced++;if(m.status==='DELIVERY_DELAYED')x.deferred++;map.set(d,x);});return[...map.entries()].sort((a,b)=>b[1].total-a[1].total).slice(0,12);},[shown]);
 const nav:Array<[Section,string]>=[['overview','Home'],['queues','Queues'],['domains','Domains'],['vmtas','Virtual MTAs'],['jobs','Jobs'],['reputation','Reputation'],['logs','Logs']];
 const kpis=[['Sent',fmt(sent),'messages',Mail],['Delivered',`${fmt(delivered)} · ${pct(stats?.deliveryRate)}`,'delivery rate',CheckCircle2],['Bounced',`${fmt(bounced)} · ${pct(stats?.bounceRate)}`,'bounce rate',XCircle],['Opens',fmt(stats?.opens),'tracked opens',Activity],['Clicks',fmt(stats?.clicks),'tracked clicks',Zap],['Queue',fmt(queue),'KumoMTA live queue',Clock3],['In Flight',fmt(inFlight),'live outbound',Server],['Send Rate',`${rate.toFixed(2)} msg/s`,'live',Gauge],['Connections',fmt(active),`${fmt(idle)} idle`,Server],['Failed',fmt(stats?.failed),'messages',AlertTriangle]] as const;
 return <div className="min-h-full bg-[#07080b] text-zinc-100"><div className="sticky top-0 z-20 bg-[#0c0e12]/95 backdrop-blur border-b border-[#242832] px-4 py-2 flex items-center gap-1 overflow-x-auto">{nav.map(([key,label])=><button key={key} onClick={()=>setSection(key)} className={`px-4 py-2 rounded-md text-xs font-semibold whitespace-nowrap ${section===key?'bg-[#7f1d1d] text-white':'text-zinc-400 hover:bg-[#171a20] hover:text-white'}`}>{label}</button>)}<div className="ml-auto flex items-center gap-2"><span className="w-2 h-2 rounded-full bg-emerald-400 animate-pulse"/><span className="text-[10px] text-emerald-400 font-bold">LIVE 2s</span></div></div>
 <div className="p-4 md:p-6 max-w-[1700px] mx-auto space-y-5"><header className="flex flex-wrap justify-between items-center gap-3"><div><div className="flex items-center gap-3"><h1 className="text-xl font-bold">Power MTA Operations</h1><span className={`px-2 py-1 rounded text-[10px] font-bold ${health[1]}`}>{health[0]}</span></div><p className="text-xs text-zinc-500 mt-1">KumoMTA + EmailOps · real server telemetry</p></div><div className="flex gap-2"><button onClick={()=>{onRefresh();refreshLive();}} className="px-3 py-2 rounded-md bg-[#15181e] border border-[#2a2e38] text-xs"><RefreshCw className={`w-3.5 h-3.5 inline mr-1.5 ${isLoading?'animate-spin':''}`}/>Refresh</button><button onClick={onNavigateToSend} className="px-3 py-2 rounded-md bg-[#991b1b] text-xs font-bold"><Mail className="w-3.5 h-3.5 inline mr-1.5"/>Send Test</button></div></header>
 {section==='overview'&&<><div className="grid grid-cols-2 md:grid-cols-3 xl:grid-cols-5 gap-3">{kpis.map(([label,value,meta,Icon])=><div key={label} className={`${card} p-4`}><div className="flex justify-between text-[10px] uppercase tracking-wider text-zinc-500"><span>{label}</span><Icon className="w-4 h-4 text-zinc-600"/></div><div className="text-xl font-bold mt-3">{value}</div><div className="text-[10px] text-zinc-600 mt-1">{meta}</div></div>)}</div><div className="grid xl:grid-cols-3 gap-4"><section className={`${card} xl:col-span-2 p-4`}><div className="flex justify-between mb-3"><div><h2 className="font-semibold text-sm">Live KumoMTA Traffic</h2><p className="text-[10px] text-zinc-600">Queue and delivery rate · 2 second polling</p></div><span className="text-xs font-mono text-emerald-400">{rate.toFixed(2)} msg/s</span></div><div className="h-64"><ResponsiveContainer width="100%" height="100%"><AreaChart data={samples}><CartesianGrid stroke="#20242c"/><XAxis dataKey="t" hide/><YAxis stroke="#555"/><Tooltip contentStyle={{background:'#0d0f13',border:'1px solid #2a2e38',color:'#fff'}}/><Area dataKey="rate" stroke="#dc2626" fill="#7f1d1d" fillOpacity={0.2}/><Area dataKey="queue" stroke="#f59e0b" fill="none"/></AreaChart></ResponsiveContainer></div></section><section className={`${card} p-4`}><h2 className="font-semibold text-sm">Live Health</h2><div className="space-y-3 mt-4">{[['KumoMTA',stats?.kumoHealth],['Queue',fmt(queue)],['Outbound',fmt(active)],['In flight',fmt(inFlight)],['CPU',`${n(live.kumomta_cpu_usage_percent).toFixed(1)}%`],['Metrics',live.kumomta_live?'LIVE':'FALLBACK']].map(([a,b])=><div key={String(a)} className="flex justify-between border-b border-[#20242c] pb-2 text-xs"><span className="text-zinc-500">{a}</span><span>{String(b||'—')}</span></div>)}</div></section></div><section className={card}><div className="p-4 border-b border-[#242832] flex justify-between"><h2 className="font-semibold text-sm">Recent Sending Activity</h2><span className="text-[10px] text-zinc-600">{shown.length} live messages</span></div><div className="overflow-x-auto"><table className="w-full text-xs"><thead className="bg-[#0c0e12] text-zinc-500"><tr>{['Time','Message ID','From','To','Subject','Status','Events'].map(h=><th key={h} className="text-left p-3">{h}</th>)}</tr></thead><tbody>{shown.slice(0,20).map(m=><tr key={m.id} onClick={()=>onSelectMessage(m)} className="border-t border-[#20242c] hover:bg-[#15181e] cursor-pointer"><td className="p-3">{time(m.createdAt)}</td><td className="p-3 font-mono max-w-[180px] truncate">{m.messageId}</td><td className="p-3">{m.fromEmail}</td><td className="p-3">{m.toEmail}</td><td className="p-3 max-w-[220px] truncate">{m.subject}</td><td className="p-3"><span className="px-2 py-1 rounded bg-[#1b1f27]">{m.status}</span></td><td className="p-3">{m.events?.length||0}</td></tr>)}</tbody></table>{!shown.length&&<div className="p-12 text-center text-zinc-600">No live messages yet.</div>}</div></section></>}
 {section==='queues'&&<section className={card}><div className="p-4 border-b border-[#242832]"><h2 className="font-semibold">Live Queue</h2><p className="text-xs text-zinc-600">Direct KumoMTA metrics endpoint</p></div><div className="grid grid-cols-2 md:grid-cols-4 gap-3 p-4">{[['Ready',live.kumomta_ready_queue_size],['Scheduled',live.kumomta_scheduled_queue_size],['In Flight',inFlight],['Total',queue]].map(([a,b])=><div key={String(a)} className="bg-[#0b0d10] border border-[#20242c] rounded p-4"><div className="text-[10px] text-zinc-600">{a}</div><div className="text-2xl font-bold mt-2">{fmt(b)}</div></div>)}</div></section>}
 {section==='domains'&&<section className={card}><div className="p-4 border-b border-[#242832]"><h2 className="font-semibold">Destination Domains</h2></div><div className="overflow-x-auto"><table className="w-full text-xs"><thead className="bg-[#0c0e12] text-zinc-500"><tr>{['Domain','Recipients','Delivered','Bounce','Deferred'].map(h=><th key={h} className="p-3 text-left">{h}</th>)}</tr></thead><tbody>{domains.map(([d,x])=><tr key={d} className="border-t border-[#20242c]"><td className="p-3">{d}</td><td className="p-3">{x.total}</td><td className="p-3">{pct(x.total?x.delivered/x.total*100:0)}</td><td className="p-3">{pct(x.total?x.bounced/x.total*100:0)}</td><td className="p-3">{pct(x.total?x.deferred/x.total*100:0)}</td></tr>)}</tbody></table></div></section>}
 {section==='vmtas'&&<div className="grid md:grid-cols-2 gap-4"><section className={`${card} p-5`}><h2 className="font-semibold">Virtual MTA</h2><div className="mt-5 flex justify-between"><span>KumoMTA</span><span className="text-emerald-400">{String(stats?.kumoHealth||'unknown').toUpperCase()}</span></div><div className="mt-3 text-xs text-zinc-500">SMTP active {fmt(active)} · idle {fmt(idle)}</div></section><section className={`${card} p-5`}><h2 className="font-semibold">IP Pool / Reputation</h2><p className="text-xs text-zinc-500 mt-4">Real IP/RBL/warmup values require integrations; no fake scores.</p></section></div>}
 {section==='jobs'&&<section className={card}><div className="p-4 border-b border-[#242832]"><h2 className="font-semibold">Jobs / Campaigns</h2></div>{(stats?.topCampaigns||[]).map(c=><div key={c.id} className="p-4 border-b border-[#20242c] flex flex-wrap justify-between text-xs"><b>{c.name}</b><span>Sent {fmt(c.sent)}</span><span>Delivered {fmt(c.delivered)}</span><span>Open {pct(c.openRate)}</span><span>Click {pct(c.clickRate)}</span></div>)}</section>}
 {section==='reputation'&&<div className="grid md:grid-cols-2 xl:grid-cols-4 gap-4">{[['Bounce rate',pct(stats?.bounceRate)],['Complaint rate',sent?pct(n(stats?.complaints)/sent*100):'0.00%'],['SPF/DKIM/DMARC','Domains'],['PTR/RBL','Integration required']].map(([a,b])=><div key={String(a)} className={`${card} p-5`}><div className="text-xs text-zinc-500">{a}</div><div className="text-2xl font-bold mt-3">{b}</div></div>)}</div>}
 {section==='logs'&&<section className={card}><div className="p-4 border-b border-[#242832] flex justify-between"><h2 className="font-semibold">Live Technical Logs</h2><span className="text-[10px] text-zinc-600">{logs.length} loaded</span></div><div className="divide-y divide-[#20242c]">{logs.slice(0,100).map(l=><div key={l.id} className="p-3 grid grid-cols-1 md:grid-cols-5 gap-2 text-xs"><span className="text-zinc-500">{time(l.timestamp)}</span><span>{l.service}</span><span className="font-semibold">{l.event}</span><span className={l.severity==='ERROR'?'text-red-400':l.severity==='WARN'?'text-amber-400':'text-emerald-400'}>{l.severity}</span><span className="text-zinc-400 truncate">{l.response}</span></div>)}{!logs.length&&<div className="p-10 text-center text-zinc-600">No live logs yet.</div>}</div></section>}
 <div className="text-[10px] text-zinc-600 flex justify-between"><span><span className="inline-block w-1.5 h-1.5 rounded-full bg-emerald-400 mr-1 animate-pulse"/>Messages + logs + Kumo metrics polling every 2 seconds</span><span>Power MTA Operations</span></div></div></div>;
};
