import React,{useEffect,useMemo,useState} from 'react';
import {Copy,Eye,FileCode2,Plus,Save,Send,Trash2,X} from 'lucide-react';
import {Template} from '../types';
interface Props{templates:Template[];authFetch?:(url:string,options?:RequestInit)=>Promise<Response>;onRefresh:()=>void;onTest?:(payload:any)=>Promise<void>;}
const btn='px-3 py-2 rounded-[4px] border border-[#2a3733] bg-[#131917] text-[10px] font-mono text-[#d8e6df] hover:border-[#39ff9c] transition-colors';
export const TemplatesView:React.FC<Props>=({templates,authFetch,onRefresh,onTest})=>{
 const [selected,setSelected]=useState<Template|null>(templates[0]||null); const [name,setName]=useState(''); const [subject,setSubject]=useState(''); const [html,setHtml]=useState(''); const [preheader,setPreheader]=useState(''); const [showEditor,setShowEditor]=useState(false); const [saving,setSaving]=useState(false);
 useEffect(()=>{if(selected){setName(selected.name);setSubject(selected.subject);setHtml(selected.htmlBody||'');setPreheader(selected.preheader||'')}},[selected]);
 const preview=useMemo(()=>html.replace(/\{\{\s*first_name\s*\}\}/gi,'Alaa').replace(/\{\{\s*unsubscribe_link\s*\}\}/gi,'Unsubscribe'),[html]);
 const openNew=()=>{setSelected(null);setName('New template');setSubject('');setPreheader('');setHtml('<html><body><h1>Hello {{first_name}}</h1><p>Your message starts here.</p><p>{{unsubscribe_link}}</p></body></html>');setShowEditor(true)};
 const save=async()=>{if(!authFetch||!name.trim()||!html.trim())return;setSaving(true);try{const body={name,subject,preheader,htmlBody:html,plainText:html.replace(/<[^>]+>/g,' '),variables:['first_name','unsubscribe_link'],trackOpens:true,trackClicks:true};const r=selected?await authFetch(`/api/templates/${selected.id}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}):await authFetch('/api/templates',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(r.ok){setShowEditor(false);onRefresh()}}finally{setSaving(false)}};
 const remove=async(id:string)=>{if(!authFetch||!confirm('Delete this template?'))return;const r=await authFetch(`/api/templates/${id}`,{method:'DELETE'});if(r.ok){if(selected?.id===id)setSelected(null);onRefresh()}};
 return <div className="p-6 md:p-8 max-w-[1500px] mx-auto font-mono text-[#d8e6df] space-y-5"><div className="flex flex-wrap justify-between gap-3"><div><h1 className="text-xl font-bold">// TEMPLATES</h1><p className="text-[10px] text-[#4a5a53] mt-1">Reusable HTML email assets with merge tags and live preview.</p></div><button className="px-4 py-2 rounded-[4px] bg-[#39ff9c] text-[#03140b] text-[10px] font-bold" onClick={openNew}><Plus className="w-3.5 h-3.5 inline mr-1"/>New Template</button></div>
 <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-3">{templates.map(t=><div key={t.id} className="bg-[#0f1412] border border-[#1e2825] rounded-[6px] p-4 hover:border-[#2a3733]"><div className="flex justify-between gap-2"><div className="flex gap-2"><FileCode2 className="w-4 h-4 text-[#39ff9c]"/><div><div className="text-xs font-bold">{t.name}</div><div className="text-[9px] text-[#4a5a53] mt-1">{t.subject||'No subject'}</div></div></div><div className="flex gap-1"><button title="Edit" className="p-1.5 text-[#7c9188] hover:text-white" onClick={()=>{setSelected(t);setShowEditor(true)}}><Eye className="w-3.5 h-3.5"/></button><button title="Duplicate" className="p-1.5 text-[#7c9188] hover:text-white" onClick={()=>{setSelected({...t,id:'',name:`${t.name} copy`});setShowEditor(true)}}><Copy className="w-3.5 h-3.5"/></button><button title="Delete" className="p-1.5 text-[#7c9188] hover:text-red-400" onClick={()=>remove(t.id)}><Trash2 className="w-3.5 h-3.5"/></button></div></div><div className="mt-4 h-20 rounded border border-[#1e2825] bg-white overflow-hidden p-3 text-black text-[8px]" dangerouslySetInnerHTML={{__html:(t.htmlBody||'<p>Empty template</p>').slice(0,1200)}}/><div className="mt-3 flex gap-2 text-[9px] text-[#4a5a53]"><span>OPEN {t.trackOpens?'ON':'OFF'}</span><span>CLICK {t.trackClicks?'ON':'OFF'}</span></div></div>)}</div>
 {!templates.length&&<div className="border border-dashed border-[#2a3733] rounded-[6px] py-16 text-center text-xs text-[#4a5a53]">No templates yet. Create your first reusable email.</div>}
 {showEditor&&<div className="fixed inset-0 z-50 bg-black/80 p-4 flex items-center justify-center"><div className="w-full max-w-[1400px] h-[90vh] bg-[#0b0e0d] border border-[#2a3733] rounded-[6px] flex flex-col"><div className="p-3 border-b border-[#1e2825] flex justify-between"><div className="text-xs font-bold">{selected?.id?'EDIT TEMPLATE':'NEW TEMPLATE'}</div><div className="flex gap-2"><button className={btn} onClick={()=>onTest?.({testEmail:'',htmlBody:html,subject})}><Send className="w-3 h-3 inline mr-1"/>Test</button><button className="px-3 py-2 rounded-[4px] bg-[#39ff9c] text-[#03140b] text-[10px] font-bold" onClick={save} disabled={saving}><Save className="w-3 h-3 inline mr-1"/>{saving?'Saving…':'Save'}</button><button className="p-2 text-[#7c9188]" onClick={()=>setShowEditor(false)}><X className="w-4 h-4"/></button></div></div><div className="p-3 grid grid-cols-1 md:grid-cols-3 gap-2 border-b border-[#1e2825]"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Template name" className="bg-[#070908] border border-[#1e2825] rounded p-2 text-xs"/><input value={subject} onChange={e=>setSubject(e.target.value)} placeholder="Subject line" className="bg-[#070908] border border-[#1e2825] rounded p-2 text-xs"/><input value={preheader} onChange={e=>setPreheader(e.target.value)} placeholder="Preview text" className="bg-[#070908] border border-[#1e2825] rounded p-2 text-xs"/></div><div className="flex-1 grid grid-cols-1 lg:grid-cols-2 min-h-0"><textarea value={html} onChange={e=>setHtml(e.target.value)} spellCheck={false} className="w-full h-full resize-none bg-[#070908] text-[#7c9188] p-4 font-mono text-[11px] leading-6 outline-none border-r border-[#1e2825]"/><div className="bg-white overflow-auto p-6"><div className="text-[10px] text-zinc-400 mb-3">LIVE PREVIEW</div><div className="text-black" dangerouslySetInnerHTML={{__html:preview}}/></div></div></div></div>}
 </div>;
};
